CONFIG_NET_CAPTURE=y
# CONFIG_NET_CAPTURE_LOG_LEVEL_DBG=y
# CONFIG_NET_CAPTURE_TX_DEBUG=y
CONFIG_NET_CAPTURE_BUF_COUNT=50
CONFIG_NET_CAPTURE_PKT_COUNT=50

CONFIG_NET_IF_MAX_IPV6_COUNT=3
CONFIG_NET_IF_MAX_IPV4_COUNT=3
CONFIG_NET_IF_UNICAST_IPV4_ADDR_COUNT=2

CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_INIT_TIMEOUT=0
CONFIG_NET_CONFIG_AUTO_INIT=n
CONFIG_NET_CONFIG_NEED_IPV6=y
CONFIG_NET_CONFIG_NEED_IPV4=y
CONFIG_NET_PKT_BUF_TX_DATA_POOL_SIZE=40000
CONFIG_NET_PKT_BUF_RX_DATA_POOL_SIZE=70000
