#
# USB (next) overlay for wifi/monitor sample.
#
# This is used by Zephyr's common USB sample init code
# (`zephyr/samples/subsys/usb/common/sample_usbd_init.c`) which expects the
# CONFIG_SAMPLE_USBD_* symbols below to be defined.
#

# Required by zephyr/samples/subsys/usb/common/sample_usbd_init.c
CONFIG_SAMPLE_USBD_VID=0x1915
CONFIG_SAMPLE_USBD_PID=0x521F
CONFIG_SAMPLE_USBD_MANUFACTURER="Nordic Semiconductor"
CONFIG_SAMPLE_USBD_PRODUCT="nRF Wi-Fi monitor"
CONFIG_SAMPLE_USBD_MAX_POWER=250

